### DISCUSSION TITLE
How load JSON column as an unmarshalled struct?

### DISCUSSION THREAD

**Discussion by alex-ntousias** [aarondl/sqlboiler#1058] [Q&A] [answered]
Hello everyone,

First of all congratulations for the awesome library and many thanks for supporting it. We've been using SQLBoiler in our project for more than a year now and it has been a treat!

I have a JSON column in my DB table and I want to generate the SQLBoiler model but instead of the usual `types.JSON` for that field, I want it to have the actual type that it has when unmarshalled. 

For example, let's say we have the following table:
```sql
CREATE TABLE configs (
    id character varying NOT NULL,
    display_config jsonb DEFAULT '{}'::jsonb NOT NULL
);
```

And the following struct for the display configs:
```go
type DisplayConfig struct {
  DisplayHeader bool `json:"display_header"`
  Padding int `json:"padding"`
  ...
}
```

I would like my generated `Configs` SQLBoiler struct to be something like the following:
```go
type Config struct {
  ID string `boil:"id" json:"id" toml:"id" yaml:"id"`
  DisplayConfig DisplayConfig `boil:"display_config" json:"display_config" toml:"display_config" yaml:"display_config"`
}
```

Is there any way to achieve this in SQLBoiler? 
If not, is there a specific pattern people usually use to achieve the above?

Many thanks,
Alex

**Comment by stephenafamo** [comment, marked as answer]
You can do this using in the  [`configuration file`](https://github.com/volatiletech/sqlboiler#types). For example:

```toml
[[types]]
  [types.match]
    tables = ['users']    # Leave empty to affect all columns with this name
    name = "metadata"    # Name of column to override the type
    nullable = false    # Is it nullable?

  [types.replace]
    type = "customTypes.UserMeta"    # The name of the type to replace with

  [types.imports]
    third_party = ['customTypes "github.com/path/to/custom/types"']    # The package containing your custom type
```
