### DISCUSSION TITLE
Could replaced types be pointer types?

### DISCUSSION THREAD

**Discussion by preslavrachev** [aarondl/sqlboiler#1240] [Q&A]
I was playing around with type replacements for some of our JSON column, and was curios to figure out, whether the code below would work:

```toml
[[types]]
  [types. Match]
  # match configuration ...

  [types. Replace]
    type = "*models.SomeModel"
```

turns out, it does not. From my experiments, it looks like type replacements need a concrete value type, even for nillable fields. I am aware that this is a convention that the the Go team has adopted for types whose zero value could be `NULL`, but, as Russ Cox [says](https://groups.google.com/g/golang-nuts/c/vOTFu2SMNeA/m/GB5v3JPSsicJ), a pointer could do the job equally well, and it has the advantage that one is not leaking SQL-specific types to the rest of the code.

So, my question is if it is possible to support pointer types, or if it works already, what is the specific syntax to achieve it?
