### DISCUSSION TITLE
Option to add custom build tags during generation

### DISCUSSION THREAD

**Discussion by kelzenberg** [aarondl/sqlboiler#1415] [Ideas]
I'd like to see an option that let's me add custom build tags to the generated output.

## Example Use Case

Prevent code analysis on generated files via a build tag named `codeanalysis` (inspired by [golangci-lint issue on SO](https://stackoverflow.com/a/59865597)) . The `sqlboiler.toml`config for this could look like this:
```toml
pkgname = "models"
output = "models"
wipe = true
custom-build-tags = "!codeanalysis" # comma-separated string list
```

And the generated file could look like this:
```go
// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

//go:build !codeanalysis

package models
...
```
