### ISSUE TITLE
go generate: could not find sqlboiler version in go.mod

### ISSUE THREAD

**Issue by RhykerWells** [aarondl/sqlboiler#1455]
Following the migration of the SQLBoiler module path from `github.com/volatiletech/sqlboiler/v4` to `github.com/aarondl/sqlboiler/v4`, I updated the module dependency in `go.mod` and installed the corresponding CLI version. However, when executing `go generate` to run SQLBoiler, i get the following warning:

```
Warn: could not find sqlboiler version in go.mod
```

---

**Steps to Reproduce**

1. Migrated all references from `github.com/volatiletech/sqlboiler/v4` to `github.com/aarondl/sqlboiler/v4` within the project source code and dependencies.

2. Updated `go.mod` to explicitly require the new module version:

   ```bash
   go get github.com/aarondl/sqlboiler/v4@v4.19.2
   ```

3. Installed the matching CLI version:

   ```bash
   go install github.com/aarondl/sqlboiler/v4@v4.19.2
   ```

4. Verified the installed CLI version:

   ```bash
   sqlboiler --version
   ```

   Output:

   ```
   SQLBoiler v4.19.1
   ```

5. Executed `go generate ./...`, example sqlboiler.toml file below:
```toml
add-global-variants="true"
no-hooks="true"
no-tests="true"
strict_verify_mod_version = false

[psql]
dbname="test"
host="localhost"
user="test"
pass="test"
sslmode="disable"
whitelist=["......."]
```

---

**Expected Behavior**

The SQLBoiler CLI should correctly detect the module version from `go.mod` without issuing a warning when the CLI version and module version are consistent and generate the models appropriately

---

**Environment**

* SQLBoiler CLI version: v4.19.1
* Module path in `go.mod`: `github.com/aarondl/sqlboiler/v4 v4.19.2`
* Go version: `go1.24.1 linux/arm64`
* Operating system: *Ubuntu 24.04.2 LTS aarch64*

---

Please let me know if any further details or logs would be helpful
